version: '3'

volumes:
  mysql-data:
    driver: local
  mysql-log:
    driver: local
  mysql-conf:
    driver: local

services:
  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
      - mysql-conf:/etc/mysql/conf.d
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    ports:
      - "3306:3306"
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:${MYSQL_PORT}", "--", "./streamingapp"]

  zookeeper:
    image: quay.io/debezium/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  
  kafka-connect:
    image: quay.io/debezium/connect
    depends_on:
      - kafka
    ports:
      - 8083:8083
    links:
     - kafka
     - db
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

networks:
  default:
    name: streamNet