version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: str34m
      MYSQL_DATABASE: streaming
      MYSQL_USER: streamuser
      MYSQL_PASSWORD: streampass
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
