version: '3'

volumes:
  data:

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_DATABASE}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:${MYSQL_PORT}", "--", "./streamingapp"]

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    ports:
      - 8080 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    restart: always

networks:
  default:
    name: streamNet